-- ============================================================
-- shell / 终端备选配置（当前全部为注释，需要时取消注释即可）
-- （由 lua/options.lua 通过 :runtime! lua/options/*.lua 加载）
-- ============================================================

-- local check_nushell = io.popen("nu --help")
--
-- if check_nushell and check_nushell:read() == "The nushell language and shell." then
--   vim.opt.shell = "nu"
--   -- vim.opt.sh = "nu"
--   vim.opt.shelltemp = false
--   vim.opt.shellredir = "out+err> %s"
--   -- flags for nu:
--   -- * `--stdin`       redirect all input to -c
--   -- * `--no-newline`  do not append `\n` to stdout
--   -- * `--commands -c` execute a command
--   vim.opt.shellcmdflag = "--stdin --no-newline -c"
--
--   -- disable all escaping and quoting
--   vim.opt.shellxescape = ""
--   vim.opt.shellxquote = ""
--   vim.opt.shellquote = ""
--   -- vim.fn.stdpath("data")
-- else
--   if vim.fn.has("win32") == 1 then
--     vim.opt.shell = "powershell.exe"
--   else
--     vim.opt.shell = "bash"
--   end
-- end

-- if vim.fn.has("win32") == 1 then
--   vim.opt.shell = "cmd.exe"
-- else
--   vim.opt.shell = "bash"
-- end

-- vim.opt.shadafile = "NONE"
