--stylua: ignore start
return {
  { "<leader>b", group = "Buffer" },
  { "<leader>bl", mode = { "n" }, "<Cmd>BufferList<CR>",                desc = "bufferlist"                  },
  { "<leader>bt", mode = { "n" }, "<Cmd>ASToggle<CR>",                  desc = "Toggle auto-save"            },
  { "<leader>bs", mode = { "n" }, ":lua Snacks.scratch()<CR>",          desc = "Snacks scaratch"             },
  { "<leader>bS", mode = { "n" }, ":lua Snacks.scratch.select()<CR>",   desc = "Snacks scaratch select"      },
  { "<leader>bb", mode = { "n" }, "<Cmd>BufferClose<CR>",               desc = "BufferClose"                 },
  { "<leader>ba", mode = { "n" }, "<Cmd>BufferCloseAllButCurrent<CR>",  desc = "CloseAllButCurrent"          },
  { "<leader>b1", mode = { "n" }, "<Cmd>BufferGoto 1<CR>",              desc = "BufferGoto 1", noremap = true, silent = true },
  { "<leader>b2", mode = { "n" }, "<Cmd>BufferGoto 2<CR>",              desc = "BufferGoto 2", noremap = true, silent = true },
  { "<leader>b3", mode = { "n" }, "<Cmd>BufferGoto 3<CR>",              desc = "BufferGoto 3", noremap = true, silent = true },
  { "<leader>b4", mode = { "n" }, "<Cmd>BufferGoto 4<CR>",              desc = "BufferGoto 4", noremap = true, silent = true },
  { "<leader>b5", mode = { "n" }, "<Cmd>BufferGoto 5<CR>",              desc = "BufferGoto 5", noremap = true, silent = true },
  { "<leader>b6", mode = { "n" }, "<Cmd>BufferGoto 6<CR>",              desc = "BufferGoto 6", noremap = true, silent = true },
  { "<leader>b7", mode = { "n" }, "<Cmd>BufferGoto 7<CR>",              desc = "BufferGoto 7", noremap = true, silent = true },
  { "<leader>b8", mode = { "n" }, "<Cmd>BufferGoto 8<CR>",              desc = "BufferGoto 8", noremap = true, silent = true },
  { "<leader>b9", mode = { "n" }, "<Cmd>BufferGoto 9<CR>",              desc = "BufferGoto 9", noremap = true, silent = true },
  { "<leader>b0", mode = { "n" }, "<Cmd>BufferLast<CR>",                desc = "Buffer Last",  noremap = true, silent = true },
  { "<leader>bp", mode = { "n" }, "<Cmd>BufferPrevious<CR>",            desc = "BufferPrevious",      noremap = true, silent = true },
  { "<leader>bn", mode = { "n" }, "<Cmd>BufferNext<CR>",                desc = "BufferNext",          noremap = true, silent = true },
  { "<leader>bP", mode = { "n" }, "<Cmd>BufferMovePrevious<CR>",        desc = "BufferMovePrevious",  noremap = true, silent = true },
  { "<leader>bN", mode = { "n" }, "<Cmd>BufferMoveNext<CR>",            desc = "BufferMoveNext",      noremap = true, silent = true },
  { "<leader>b!", mode = { "n" }, "<Cmd>BufferPin<CR>",                 desc = "BufferPin",           noremap = true, silent = true },
  { "<leader>b@", mode = { "n" }, "<Cmd>BufferPick<CR>",                desc = "BufferPick",          noremap = true, silent = true },
  { "<leader>b#", mode = { "n" }, "<Cmd>BufferPickDelete<CR>",          desc = "BufferPickDelete",    noremap = true, silent = true },
  }
-- stylua: ignore end
