return {
  -- 建立良好的命令工作流程 改掉坏习惯
  "m4xshen/hardtime.nvim",
  -- enabled = false,
  dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
  opts = {
    disabled_filetypes = {
      "Diffview*",
      "Dressing*",
      "Neogit*",
      "NvimTree",
      "TelescopePrompt",
      "Trouble",
      "aerial",
      "alpha",
      "checkhealth",
      "dapui*",
      "db*",
      "fugitive",
      "help",
      "httpResult",
      "lazy",
      "lspinfo",
      "mason",
      "minifiles",
      "neo%-tree*",
      "neotest%-summary",
      "netrw",
      "noice",
      "notify",
      "oil",
      "prompt",
      "qf",
      "query",
      "trouble",
      "Trouble",
      "fugitive",
      "VoltWindow",
      "undotree",
      "Outline", -- outline plugin
    },
  },
}
