require("plugins.dashboard-nvim")
require("plugins.fzf-lua")
require("plugins.neo-tree")
require("plugins.mason")
require("plugins.gitsigns")
require("plugins.nvim-lspconfig")
require("plugins.hardtime")
require("plugins.notifier")
require("plugins.nvim-surround")
-- require("plugins.slimline")
require("plugins.tiny-inline-diagnostic")
require("plugins.conform")
require("plugins.blink")
-- require("plugins.tabby") -- "InsertEnter", "CmdlineEnter"
require("plugins.render-markdown")
require("plugins.nvim-lint")
