-- require("lspconfig").lua_ls.setup({
--   settings = {
--     Lua = {
--       runtime = { version = 'LuaJIT' },
--       diagnostics = { globals = { 'vim' } },
--       workspace = {
--         checkThirdParty = false,
--         library = vim.api.nvim_get_runtime_file("", true),
--       },
--       telemetry = { enable = false },
--     },
--   },
-- })
-- vim.lsp.enable("lua_ls")
